[package]
name = "esp32-rust-mqtt"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
esp-backtrace = { version = "0.11.1", features = [
    "esp32c3",
    "panic-handler",
    "exception-handler",
    "println",
] }
esp-hal = { version = "0.17.0", features = ["esp32c3"] }
embedded-hal-nb = "1.0.0"
esp-println = { version = "0.9.1", features = ["esp32c3", "uart"] }
heapless = { version = "0.8.0", default-features = false }
smoltcp = { version = "0.11.0", default-features = false, features = [
    "proto-igmp",
    "proto-ipv4",
    "socket-tcp",
    "socket-icmp",
    "socket-udp",
    "medium-ethernet",
    "proto-dhcpv4",
    "socket-raw",
    "socket-dhcpv4",
] }

compiler_builtins = { version = "=0.1.109", optional = true }
rustc-demangle = { version = "0.1.24", optional = true }
object = { version = "=0.32.2", optional = true }
libc = { version = "=0.2.153", optional = true }
dlmalloc = { version = "0.2.6", optional = true }
addr2line = { version = "=0.21.0", optional = true }
miniz_oxide = { version = "=0.7.2", optional = true }
hermit-abi = { version = "0.3.9", optional = true }
r-efi = { version = "=4.4.0", optional = true }
r-efi-alloc = { version = "1.0.0", optional = true }
wasi = { version = "=0.11.0", optional = true }
fortanix-sgx-abi = { version = "0.5.0", optional = true }
getopts = { version = "0.2.21", optional = true }
allocator-api2 = { version = "0.2.18", optional = true }
unwinding = { version = "0.2.1", optional = true }
memchr = { version = "=2.5.0", optional = true }
embedded-io = "0.6.1"

[dependencies.esp-wifi]
version = "0.5.1"
features = ["esp32c3", "wifi-default"]

[profile.dev.package.esp-wifi]
opt-level = 3

[profile.dev]
lto = "off"
[profile.release]
lto = "off"

[features]
nix =  [
    "dep:allocator-api2", 
    "dep:compiler_builtins", 
    "dep:rustc-demangle", 
    "dep:object", 
    "dep:libc", 
    "dep:dlmalloc", 
    "dep:addr2line", 
    "dep:miniz_oxide", 
    "dep:hermit-abi", 
    "dep:r-efi", 
    "dep:r-efi-alloc", 
    "dep:wasi", 
    "dep:fortanix-sgx-abi", 
    "dep:getopts", 
    "dep:allocator-api2", 
    "dep:unwinding", 
    "dep:memchr",
]
