name: "Build project with nix"

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v11
      - name: Build package
        run: SSID=foo PASSWORD=bar nix build --impure
